service: aws-lambda-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  memorySize: 256
  stage: dev

functions:
  getUsuarios:
    handler: index.getUsuarios
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
